### ISSUE TITLE
[Bug] Equality test: failures => '0' is not of type integer

### ISSUE THREAD

**Issue by TimoKruth** [tglunde/dbt-exasol#17]
Hi,
I have an [issue](https://github.com/dbt-labs/dbt-core/issues/4335) with dbt-core/dbt-utils equality tests.
They have refered me here as they think it must be something with the adapter. When I run the sql within exasol outside of dbt I get a decimal. Can you verify the problem somehow? I am not really able to verify what the code does since I am not that deep inside of debugging the python code behind dbt. 
I would really appreciate any help or even just if you can reproduce. I didn't copy all of the issue into this one because I already replicated it from utils to core. 
If I can help in any way, please let me know.

Am looking forward to any help.

Greetings Timo Kruth

**Comment by TimoKruth** [comment]
Okay I found a way to solve my problem.
When I manualy cast the output of the `fail_calc` function of the test to `INT` it works as expected.
The difference in the value of `failures` from exasol is: In the old version it returns a `DECIMAL` in the new casted version it returns `BIGINT`.

**Comment by tglunde** [comment]
Hi Timo,
this unfortunately is a tough one. We did manage to reproduce, but could not get enough detailed visibility in order to explain or get closer to a solution. 
Honestly it has been a while ago since we looked into it. Currently we are trying to get the support for dbt-exasol to a new level and eventually also have it verified. Therefor I will be working on it more and will definitely also look out for this one.

Just to let you know and greetings,
Torsten

**Comment by tglunde** [comment]
Hi @TimoKruth ,

as mentioned in [pyexasol#95 ](https://github.com/exasol/pyexasol/issues/95), we think this issue is solved with todays release of dbt-exasol 1.2.1, since we now explicitly cast values from resultsets in our adapter implementation to Decimal in case of BIGINT or DECIMAL values that get encoded as strings in pyexasol - as discussed in above issue. 

We will try to add a test for this issue in the next steps as we also need to add some basic test left for full support of dbt 1.2.x - but we also need to add v1.3 support already. 

If you find the time to retest in the meantime, please let us know here.

Regards, Torsten

**Comment by tglunde** [comment]
I actually tested this and we are confident that dbt-exasol 1.2.1 actually solves this issue.

**Comment by TimoKruth** [comment]
Hej, great that it is solved. I really appreciate it. Will test it as soon as I can update dbt to the corresponding version.
